version: '3.8'

services:
  app:
    build: .
    container_name: almanaque_nautico_roa
    
    volumes:
      - .:/app
      # Evitar que entornos virtuales locales contaminen el contenedor
      - /app/.venv
      - /app/venv

    command: sleep infinity
    # Para ejecutar la app: python modern/app.py
