services:
  app:
    build: .
    image: almanaque_nautico_roa
    container_name: almanaque_nautico_roa
    
    volumes:
      - .:/app
      # Evitar que entornos virtuales locales contaminen el contenedor
      - /app/.venv
      - /app/venv

    ports:
      - "8501:8501"

    command: sleep infinity
    # Para ejecutar la app: python modern/app.py
